server:
  port: 8080

spring:
  application:
    name: popcorn-palace
  datasource:
    url: jdbc:postgresql://localhost:5432/popcorn-palace
    username: popcorn-palace
    password: popcorn-palace
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10  # Optimize connection pooling
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
  jpa:
    database: POSTGRESQL
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never  
  management:
  endpoints:
    health:
      show-details: always  # Show full health details
    web:
      exposure:
        include: "*"
  logging:
    level:
      root: DEBUG


