-- Drop tables if they already exist (order matters because of foreign keys)
DROP TABLE IF EXISTS booking;
DROP TABLE IF EXISTS showtime;
DROP TABLE IF EXISTS movie;

-- Create the movie table
CREATE TABLE movie (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    genre VARCHAR(255),
    duration INT,
    rating DOUBLE PRECISION,
    release_year INT
);

-- Create the showtime table
CREATE TABLE showtime (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT,
    theater VARCHAR(255) NOT NULL,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    price DOUBLE PRECISION,
    CONSTRAINT fk_movie FOREIGN KEY (movie_id) REFERENCES movie(id)
);

-- Create the booking table with a unique constraint to prevent duplicate seat bookings
CREATE TABLE booking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    showtime_id BIGINT,
    seat_number INT,
    customer_name VARCHAR(255),
    CONSTRAINT fk_showtime FOREIGN KEY (showtime_id) REFERENCES showtime(id),
    CONSTRAINT unique_showtime_seat UNIQUE (showtime_id, seat_number)
);

